### ISSUE TITLE
Does this plugin solves the problem of dependencies not found on jcenter?

### ISSUE THREAD

**Issue by am** [dpa99c/cordova-android-firebase-gradle-release#1]
I've recently been doomed by a problem where gradle cannot find the dependencies on jcenter:

```
Could not resolve all files for configuration ':debugCompileClasspath'.
Could not find firebase-iid.aar (com.google.firebase:firebase-iid:11.8.0).
Searched in the following locations:
https://jcenter.bintray.com/com/google/firebase/firebase-iid/11.8.0/firebase-iid-11.8.0.aar
(...)
```
I've reached this plugin following an answer I've got from [stackoverflow question](https://stackoverflow.com/questions/52953962/how-to-extend-cordova-build-gradle-to-change-repositories/52972589) but after installing the plugin the error persists. 

I would like to know if the intention of the plugin is to solve the problem I described.

Thank you!

**Comment by dpa99c** [comment]
The intention of this plugin is to override the version of the Firebase library specified by other plugins in order to align them and therefore solve build problems caused by Gradle version conflicts.

However, the plugin does [specific the maven repository](https://github.com/dpa99c/cordova-android-firebase-gradle-release/blob/master/cordova-android-firebase-gradle-release.gradle#L3) in its Gradle config, so may have the side effect of fixing build failures caused by the jcenter repo. However, this is not the primary intention of this plugin.

**Comment by am** [comment]
Thank you @dpa99c for clear this doubt. What is still not clear to me is why after adding the plugin it still searches for firebase dependency on `jcenter`.

Is there any setting on the project that I need to take care to avoid this to happen? Is there any gradle cache that could cause this issue?
